### ISSUE TITLE
registry sync error -- database is locked

### ISSUE THREAD

**Issue by vjcitn** [tudo-r/BatchJobs#58]
never ran into this before ... is there a relevant retry option?  this is occuring in a multicore
setting 

> fdbp = storeToFDRByProbe( mm, xprobs=c(seq(.025,.975,.025),.99))
Error in value[[3L]](cond) : 
  Error syncing registry (Error in sqliteSendQuery(con, statement, bind.data): rsqlite_query_send: could not execute1: database is locked
)

> sessionInfo()
R Under development (unstable) (2014-11-04 r66931)
Platform: x86_64-unknown-linux-gnu (64-bit)

locale:
 [1] LC_CTYPE=en_US.ISO8859-1    LC_NUMERIC=C               
 [3] LC_TIME=en_US.ISO8859-1     LC_COLLATE=en_US.ISO8859-1 
 [5] LC_MONETARY=en_US.ISO8859-1 LC_MESSAGES=C              
 [7] LC_PAPER=C                  LC_NAME=C                  
 [9] LC_ADDRESS=C                LC_TELEPHONE=C             
[11] LC_MEASUREMENT=C            LC_IDENTIFICATION=C        

attached base packages:
[1] stats     graphics  grDevices datasets  utils     tools     methods  
[8] base     

other attached packages:
[1] eqtlStore_0.1.7      BatchJobs_1.5        BBmisc_1.8          
[4] BiocParallel_1.0.0   knitr_1.8            weaver_1.32.0       
[7] codetools_0.2-9      digest_0.6.4         BiocInstaller_1.16.1

loaded via a namespace (and not attached):
 [1] acepack_1.3-3.3          annotate_1.44.0          AnnotationDbi_1.28.1    
 [4] base64enc_0.1-2          biglm_0.9-1              Biobase_2.26.0          
 [7] BiocGenerics_0.12.1      biomaRt_2.22.0           Biostrings_2.34.0       
[10] biovizBase_1.14.0        bit_1.1-12               bitops_1.0-6            
[13] brew_1.0-6               BSgenome_1.34.0          caTools_1.17.1          
[16] checkmate_1.5.0          chron_2.3-45             cluster_1.15.3          
[19] colorspace_1.2-4         data.table_1.9.4         DBI_0.3.1               
[22] dichromat_2.0-0          evaluate_0.5.5           fail_1.2                
[25] fastmatch_1.0-4          ff_2.2-13                ffbase_0.11.3           
[28] foreach_1.4.2            foreign_0.8-61           formatR_1.0             
[31] Formula_1.1-2            gdata_2.13.3             genefilter_1.48.1       
[34] GenomeInfoDb_1.2.3       GenomicAlignments_1.2.1  GenomicFeatures_1.18.2  
[37] GenomicRanges_1.18.1     GGBase_3.28.0            ggplot2_1.0.0           
[40] GGtools_5.3.9            gplots_2.14.2            grid_3.2.0              
[43] gtable_0.1.2             gtools_3.4.1             Gviz_1.10.2             
[46] hexbin_1.27.0            Hmisc_3.14-5             IRanges_2.0.0           
[49] iterators_1.0.7          KernSmooth_2.23-13       lattice_0.20-29         
[52] latticeExtra_0.6-26      MASS_7.3-35              Matrix_1.1-4            
[55] matrixStats_0.10.3       munsell_0.4.2            nnet_7.3-8              
[58] parallel_3.2.0           plyr_1.8.1               proto_0.3-10            
[61] RColorBrewer_1.0-5       Rcpp_0.11.3              RCurl_1.95-4.3          
[64] reshape2_1.4             R.methodsS3_1.6.1        ROCR_1.0-5              
[67] rpart_4.1-8              Rsamtools_1.18.2         RSQLite_1.0.0           
[70] rtracklayer_1.26.2       S4Vectors_0.4.0          scales_0.2.4            
[73] sendmailR_1.2-1          snpStats_1.16.0          splines_3.2.0           
[76] stats4_3.2.0             stringr_0.6.2            survival_2.37-7         
[79] VariantAnnotation_1.12.4 XML_3.98-1.1             xtable_1.7-4            
[82] XVector_0.6.0            zlibbioc_1.12.0

**Comment by mshvartsman** [comment]
I'm seeing the same issues here running with an SGE back end, without mlr, on R 3.1.1 on CentOS, BatchJobs 1.5 with RSQLite_1.0.0. 

At first we thought this was an NFS mount issue and somehow having clobbering / write locks issue, but I’m not hammering the file server nearly hard enough for this to be the case (each job is about a minute long and I am using 10-job chunks). We also tried a different file server, with the same result. `staged.queries=TRUE` and `fs.timeout=10` don’t help. 

Also, not sure if this is relevant but the first time I see just a single: 
```
> showStatus(reg)
Syncing registry ...
Error in value[[3L]](cond) :
  Error syncing registry (Error in sqliteSendQuery(con, statement, bind.data): rsqlite_query_send: could not execute1: database is locked
```
... and then on subsequent times, it repeats slightly differently (as I am guessing it repeatedly sleeps and queries). 
```
Syncing registry ...
Error in sqliteSendQuery(con, statement, bind.data) :
  error in statement: database is locked
Error in sqliteSendQuery(con, statement, bind.data) :
  error in statement: database is locked
...
```

**Comment by berndbischl** [comment]
1)  Maybe most important: How reliably can you reproduce this?

2) I don't really get this: With stage.queries you ONLY do DB operations on the master.
So no "hammering of the DB", no matter how hard you try, there are is no dreaded parallel DB access.
Which would imply that RSqlite leaves the DB in a locked state even though there were only sequential osp on it on the master ?

**Comment by berndbischl** [comment]
Are you using something like a terminal multiplexer?
I mean you are only having 1 R session open where you operate on the reg? Just to make sure you are not submitting jobs in one session and calling showStatus at the same time in another one.

**Comment by berndbischl** [comment]
Hmmmm................

Do you see 4) here?

http://www.sqlite.org/cvstrac/wiki?p=DatabaseIsLocked

> fcntl(3, F_SETLK call on DB file fails. This could be caused by an NFS locking issue, for example.
> One solution for this issue, is to mv the DB away, and copy it back so that it has a new Inode value.

Can it be this?

**Comment by berndbischl** [comment]
Hmm, but my last comment is stupid right? Again, that issue should only occur if we would acces the DB from multiple processes, which stage.queries does not do?

**Comment by mshvartsman** [comment]
1. Reproduces reliably on the cluster . Also came up but not every time with clusterFunctionsMulticore on a single 8-core node on our cluster. 
2. I think I might have misunderstood what stage.queries does. I thought the workers still talk to the db once per chunk (vs once per job) but from your answer I think they just don't do this at all (which is great!). 

I was running under `screen` but only one shell had an R process open and interacting with the registry. Anyway, I just now replicated it running without screen.

**Comment by mllg** [comment]
> Which would imply that RSqlite leaves the DB in a locked state even though there were only sequential osp on it on the master ?

I think this can still happen if there is a small delay on your I/O. But I'm wondering why our retry mechanism seems to be broken. We grep on "lock", and after 200 retries we should throw this exception:

> dbDoQueries: max retries (%i) reached, database is still locked!

Just a wild guess, but probably `dbGetConnection` nowadays throws the lock error. We should catch this now with 86fba147a9386528566958c8c13d377dfc8a4cd9.

**Comment by berndbischl** [comment]
Now reading this, maybe it helps:

http://beets.radbox.org/blog/sqlite-nightmare.html

**Comment by mllg** [comment]
Note that we still access the DB on the nodes in ro mode which should result in a shared lock. This might still have an impact on the master which tries to get a reserved (or exclusive?) lock, but at least should not influence other slave processes.

As far as I understand this issue by combining all the reports (thanks guys!), the exception occurs in this scenario:

slave processes query the DB while the master process tries to writes in either `submitJobs` or `waitForJobs`/`syncRegistry`. IMHO we cannot avoid a lock here, but we really should catch such errors on the master and retry. Lets hope my last commit is working.

**Comment by berndbischl** [comment]
@mshvartsman  Can you please check whether Michel's fix helps?

For future reference:
Here is a last measure, to help with that problem: We might roll out the result of the READ ops for the slaves as permanent objects on disk under the "jobs" dir. then we would have exactly 0 DB ops on the slave. I don't like this as it is terrible inefficient, but as an emergency option we could try it.
Lets hope we don't have to...

The other option would be to support a real DB sever. This is some work. But the real problem is:
We don't know how many users would actually be able to set one up for their cluster.

**Comment by vjcitn** [comment]
The last time I tried to do a big application it was easy to trigger the
bug, and so I did the work through another approach.  To establish
reproducibility it was my plan to create an EC2 cluster based on the
Bioconductor AMI and show how to trigger it.  Is this a relevant approach?
I have yet to install Michel's fix but assuming I am able to generate the
error in such a context would that be useful?

**Comment by berndbischl** [comment]
> in such a context would that be useful?

Probably. In that case could you give us live access to the cluster for at least a reduced amount of time?

**Comment by berndbischl** [comment]
Ah, i am going to bed, I am only writing idiotic stuff.

 EC2 is definitely useful.

1) If you reproduce the bug on EC2 we can create our own account, copy your example and debug it

2) An EC2 demo, how to use BJ with it, should be written anyway.

(I used BJ on Azure a couple of weeks ago, but that was so simple i did not even think about writing it up. Maybe I still should have)

**Comment by vjcitn** [comment]
OK, I will let you know the outcome.  It should happen next week.

**Comment by mshvartsman** [comment]
I installed the version of BatchJobs with the latest changes and am still seeing the issue. Occasionally (but not each time) quitting and restarting R lets me reconnect. 

The NFS mounts I'm using are set up to maximize transfer speed rather than minimize latency -- I will investigate on my end the possibility that the lock / unlocks are arriving out of order. That said, if a ro lock by the slaves doesn't prevent other reads and writes by the master, then it would imply that the master is causing the issue by itself. And based on my limited understanding of how things work, I would be surprised if the master alone writes fast enough to mess with the caching. Is this making sense or should I keep pursuing the NFS question? 

As far as the USLEEP sqlite issue @berndbischl brought up, I think RSQLite ships with its own copy of sqlite (is this correct?), and does not include -DHAVE_USLEEP=1 in its Makevars there, so it's relying on the system to have it properly set. As far as I can tell, my system defines _GLIBCXX_HAVE_USLEEP but not plain old HAVE_USLEEP, so maybe that is the issue. I will investigate further.

**Comment by mschubert** [comment]
Trying same test a above with 86fba147a9386528566958c8c13d377dfc8a4cd9, still the same error:

```r
  Error syncing registry (Error in sqliteSendQuery(con, statement, bind.data):
rsqlite_query_send: could not execute1: database is locked
)
15: stop(obj)
14: stopf("Error syncing registry (%s)", e)
13: value[[3L]](cond)
12: tryCatchOne(expr, names, parentenv, handlers[[1L]])
11: tryCatchList(expr, classes, parentenv, handlers)
10: tryCatch(dbDoQueries(reg, unlist(queries[ok]), "rw"), error = function(e)
          stopf("Error syncing registry (%s)", e))
9: syncRegistry(reg)
8: withCallingHandlers(expr, message = function(c) invokeRestart("muffleMessage"))
7: suppressMessages(syncRegistry(reg))
6: waitForJobs(reg, ids = getJobIds(reg))
```

**Comment by berndbischl** [comment]
We really need a system where we can debug this live. I never really encounter this on our cluster(s) and we use NFS as well.

**Comment by vjcitn** [comment]
WIth current infrastructure, I am unable to reproduce the problem I reported.  Therefore at the moment I cannot contribute to the investigation.  Of course I will make an EC2 instance with a reproducible error if I see it again.

**Comment by mshvartsman** [comment]
As far as I can tell I have excluded the HAVE_USLEEP possibility, by modifying sqlite.c to with `#if defined(_GLIBCXX_HAVE_USLEEP) && _GLIBCXX_HAVE_USLEEP #define HAVE_USLEEP 1#endif` and recompiling RSQLite with the modified sqlite. I'm trying to find time on our cluster admin's schedule to confirm with him that I'm `module load`ing a libc that indeed defines this macro. 

But I'm still seeing the issue. More importantly, on my latest sim (about an order of magnitude bigger than before, ~40K jobs in 10-job chunks, a few minutes per job), I'm seeing jobs expire after timing out because of database locks. I think this should happen if something has a pending or exclusive lock that's preventing the slaves from grabbing a shared read lock. Is there any chance that slaves aren't obeying the staged queries setting, or some other reason slaves would get a non-shared lock? I am suspecting the slaves because (a) as far as I can tell, this happened overnight when I wasn't doing anything on the master (i.e. no waitForJobs() running) and (b) this happened at 40K jobs but not 4K jobs, and if I understand correctly the master shouldn't care about how many slaves are running. 

I wish I could help you replicate this. Is there a db log of some sort that I could provide that would help?

**Comment by mschubert** [comment]
Following my last test with 86fba147a9386528566958c8c13d377dfc8a4cd9, I now ran 30 x (200 jobs/chunk * 38 chunks) *without* error using rev 1cc6cb41149478813a87a11ea989b2ce434a513b.

Looking at the diff, these lines might have fixed it - can others confirm?

```diff
diff --git a/R/database.R b/R/database.R
index 8693254..5fcb9e2 100644
--- a/R/database.R
+++ b/R/database.R
@@ -13,7 +13,10 @@ dbGetConnection = function(drv, ...) {
 dbGetConnection.SQLiteDriver = function(drv, reg, flags = "ro", ...) {
   flags = switch(flags, "ro" = SQLITE_RO, "rw" = SQLITE_RW, "rwc" = SQLITE_RWC)
   opts = list(dbname = file.path(reg$file.dir, "BatchJobs.db"), flags = flags, drv = drv)
-  do.call(dbConnect, args = c(reg$db.options, opts))
+  con = do.call(dbConnect, args = c(reg$db.options, opts))
+  res = dbSendQuery(con, "PRAGMA busy_timeout=5000")
+  dbClearResult(res)
+  return(con)
 }
```

**Comment by mllg** [comment]
> Following my last test with 86fba14, I now ran 30 x (200 jobs/chunk * 38 chunks) without error using rev 1cc6cb4.
> 
> Looking at the diff, these lines (in dd5dd7b) might have fixed it - can others confirm?

Thanks for reporting in.

I've additionally enabled WAL journaling in 1068b3252005f9bff8aa851d09304afb168a9e47 which *should* make concurrent access even more reliable. As soon as we got more feedback that the database issues are solved (or at least less likely), we will release a new version to CRAN.

**Comment by mllg** [comment]
You can now set custom pragmas in your config (cf a80398373b4c371a4d6a263d256487bac3972072).
I've set `busy_timeout` as default in 5d57457553a0f4af638939c15264cd79986a4dec, you can try the WAL journal by setting
```r
db.options = list(pragmas = c("busy_timeout=5000", "journal_mode=WAL"))
```

If we get reports that WAL is safe to use, this will likely become the default journal in a future version. 
@berndbischl Can we push a new version to CRAN soon?

**Comment by berndbischl** [comment]
I am preparing the release 1.6.

Thx @mllg  for all this work.

Does anybody still see errors / problems? 

Or can we close here for now?

**Comment by mshvartsman** [comment]
Sorry, have been at a conference and pushing on other projects and have not been able to test the recent changes. Just started a test with ~40K jobs (25 jobs / chunk) with the db.options @mllg suggested. Will let you know if I can get through it without db timeouts.

**Comment by berndbischl** [comment]
I am closing this now. But please reopen and inform us if problems still occur.

The new code is in release 1.6 on CRAN

**Comment by vjcitn** [comment]
I have run into this again, with a batchMapResults on a registry for 11000
jobs.

The mapped function implies very short job runtimes.  I will try adding a
sleep into the function

to see if this can be avoided.

Error in sqliteSendQuery(con, statement, bind.data) :

  rsqlite_query_send: could not execute1: database is locked


> sessionInfo()

R version 3.2.2 Patched (2015-08-18 r69117)

Platform: x86_64-pc-linux-gnu (64-bit)


locale:

 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C

 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8

 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8

 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C

 [9] LC_ADDRESS=C               LC_TELEPHONE=C

[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C


attached base packages:

 [1] stats4    parallel  stats     graphics  grDevices datasets  utils

 [8] tools     methods   base


other attached packages:

 [1] GenomicRanges_1.21.21 GenomeInfoDb_1.5.13   IRanges_2.3.18

 [4] S4Vectors_0.7.14      BiocGenerics_0.15.6   gQTLBase_1.1.18

 [7] BatchJobs_1.6         BBmisc_1.9            knitr_1.11

[10] weaver_1.35.0         codetools_0.2-14      digest_0.6.8

[13] BiocInstaller_1.19.14


loaded via a namespace (and not attached):

 [1] futile.logger_1.4.1        XVector_0.9.3

 [3] base64enc_0.1-3            bitops_1.0-6

**Comment by mshvartsman** [comment]
I mentioned this in the email list, but just adding here for completeness: this problem went away for me after moving my registry from NFS to GPFS. Potential confound: this also meant moving to another cluster/scheduler (SGE->SLURM), but I don't see how that should make a difference. 

If nothing else suggested above works for you, you might see if you can move your registry to another filesystem.

**Comment by vjcitn** [comment]
thanks.  in this case a

job.delay = function(n,i) runif(1,1,3)

setting seems to have done the trick.

**Comment by matthiasheinig** [comment]
Hi, 
I also ran into this problem (database locked) with waitForJobs using BatchJobs 1.6 (as far as I understood, that version should already have fixed the issue right?) I am running 1000 jobs on a SGE cluster with NFS storage. 

I would be grateful for any advise. 

Thanks,
Matthias

This is the exact error message:
Error syncing registry (Error in sqliteSendQuery(con, statement, bind.data): rsqlite_query_send: could not execute1: database is locked

Here is the sessionInfo():
R version 3.1.2 (2014-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] BatchJobs_1.6    BBmisc_1.9       data.table_1.9.4 MatrixEQTL_2.1.1

loaded via a namespace (and not attached):
 [1] DBI_0.3.1       RSQLite_1.0.0   base64enc_0.1-3 brew_1.0-6
 [5] checkmate_1.6.2 chron_2.3-45    digest_0.6.3    fail_1.2
 [9] parallel_3.1.2  plyr_1.8        reshape2_1.2.2  sendmailR_1.2-1
[13] stringr_0.6.2   tools_3.1.2

**Comment by vjcitn** [comment]
Try adding a setting for job.delay to the submitJobs call.  I posted my
solution previously.
It may need tweaking for your specific setup but job.delay = function(n,i)
runif(1,1,3) got me
around the error.  the default if you set job.delay=TRUE can lead to very
long delays, so i would
not recommend that, and i found that using runif(1, 0, .5) did not avoid
the problem.  Luck
may play a role.
